overrides:
  ceph-deploy:
    conf:
      global:
        ms die on skipped message: false
tasks:
- ssh-keys:
- ceph-deploy:
    fs: btrfs
- rbd:
    all:
      image_size: 20480
- workunit:
    clients:
      all:
        - suites/iozone.sh
